version: "3.8"

services:
  db:
    build: ./database
    container_name: organization-registry-db
    hostname: organization-registry-db
    restart: always
    environment:
      POSTGRES_DB: organization-registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432

  dba:
    image: dpage/pgadmin4:5.6
    container_name: organization-registry-dba
    hostname: organization-registry-dba
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.be
      PGADMIN_DEFAULT_PASSWORD: dev
    ports:
      - 8001:80
    depends_on:
      - db
    links:
      - db